name: MSYS2 Testing

on:
  push:
  pull_request:

jobs:


  win-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { msystem: MINGW64, arch: x86_64 }
          - { msystem: MINGW32, arch: i686   }
    name: ${{ matrix.msystem }} | ${{ matrix.arch }} | build
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_INSTALLS: ${{ matrix.msystem }}
    steps:

    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: >
          base-devel
          mingw-w64-${{ matrix.arch }}-toolchain
          tree

    - name: Build
      run: |
        cd msys2
        makepkg-mingw --noconfirm --noprogressbar -sCLf

    - name: Package contents
      run: |
        cd msys2
        tree pkg

    - uses: actions/upload-artifact@v2
      with:
        path: msys2/*.zst


  win-test:
    needs: win-build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { msystem: MINGW64, arch: x86_64 }
          - { msystem: MINGW32, arch: i686   }
    name: ${{ matrix.msystem }} | ${{ matrix.arch }} | test
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true

    - uses: actions/download-artifact@v2

    - run: pacman -U --noconfirm --noprogressbar artifact/*.zst

    - run: nextpnr-ice40 --help
